### ISSUE TITLE
[WIP] vectorIcons Todo

### ISSUE THREAD

**Issue by ztNFny** [ztNFny/cgeo#10]
Must have
- [x] https://github.com/cgeo/cgeo/issues/11592
- [x] https://github.com/cgeo/cgeo/issues/11591

Medium
- [x] https://github.com/cgeo/cgeo/issues/11545 / https://github.com/cgeo/cgeo/issues/11699
- [x] https://github.com/cgeo/cgeo/issues/11616
- [x] https://github.com/cgeo/cgeo-guide/issues/42
- [x] https://github.com/cgeo/cgeo/issues/11424
- [x] https://github.com/cgeo/cgeo/issues/11732

Low
- [x] https://github.com/cgeo/cgeo/issues/11615
- [x] https://github.com/cgeo/cgeo/issues/11715
